import json
import os
import requests
from dotenv import load_dotenv
from google import genai
import requests
from github import Github
import time

load_dotenv()

key = os.getenv("TRELLO_API_KEY")
token = os.getenv("TRELLO_TOKEN")
board_id = os.getenv("TRELLO_BOARD_ID")
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

url = f"https://api.trello.com/1/boards/{board_id}/cards"

query = {
    'key': key,
    'token': token
}

response = requests.get(url, params=query)

def validate_card(card):
    info = []
    if not card['idAttachmentCover']:
        info.append("an image attachment (UI Mockup)")
    desc = card['desc']

    return True

def check_with_gemini(card):
    prompt = f"Audid this task: {card}. Is a tech stack mentioned? Return JSON {{'ready': bool, 'missing':str}}"
    response = client.models.generate_content(
        model='gemini-1.5-flash',
        contents=prompt,
        config={'response_mime_type': 'application/json'}
    )

    return json.loads(response.text)

def post_trello_comment(card_id, comment):
    url = f"https://api.trello.com/1/cards/{card_id}/actions/comments"
    query = {
        'key': key,
        'token': token,
        'text': comment
    }
    response = requests.post(url, params=query)
    
def get_checklist_items(checklist_id):
    checklist_content = []
    url = f"https://api.trello.com/1/checklists/{checklist_id}"
    query = {
        'key': key,
        'token': token
    }
    response = requests.get(url, params=query)
    if response.status_code == 200:
        checklist = response.json()
        items = [item['name'] for item in checklist.get('checkItems', [])]
        checklist_content.append(f"Checklist: {checklist['name']} with items: {', '.join(items)}")
    
    return "\n".join(checklist_content)

def commit_code_to_github(repo_name, file_path, content, task_name):
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_user().get_repo(repo_name)
    branch_name = f"ai-build-{task_name.lower().replace(' ', '-')}-{int(time.time())}"
    # in the future we can have the user set the base branch
    base_branch = "main"
    try:
        sb = repo.get_branch(base_branch)
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sb.commit.sha)
        repo.create_file(
            path=file_path,
            message=f"AI Build: {task_name}",
            content=content,
            branch=branch_name
        )
        pr = repo.create_pull(
            title=f"AI Suggestion: {task_name}",
            body=f"This PR was automatically generated by the PM Agent for the Trello task: {task_name}.",
            head=branch_name,
            base=base_branch
        )
        return pr.html_url
    except Exception as e:
        print(f"Error committing to GitHub: {e}")
        return None


if response.status_code == 200:
    temp = response.json()
    for card in temp:
        if card['idList'] == '68bdf9ec4b3199a98b99d200':
            audit = check_with_gemini(card)
            if not audit['ready']:
                post_trello_comment(card['id'], f"I need more info: {audit['missing']}")
            else:
                generate_code = client.models.generate_content(
                    model='gemini-1.5-flash',
                    contents=f"Generate code for this task: {card['name']} with description: {card['desc']} and checklist items: {get_checklist_items(card['idChecklists'][0])}",
                ).text
                file_name = f"src/{card['name'].replace(' ', '_')}.py"
                commit_code_to_github("PM_Agent_Repo", file_name, generate_code, f"AI Build: {card['name']}")
else:
    print(response.text)