import json
import os
import requests
from dotenv import load_dotenv
from google import genai
from github import Github, Auth
import time
import io
import boto3
from PIL import Image
import csv 
from datetime import datetime

load_dotenv()

key = os.getenv("TRELLO_API_KEY")
token = os.getenv("TRELLO_TOKEN")
board_id = os.getenv("TRELLO_BOARD_ID")
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

url = f"https://api.trello.com/1/boards/{board_id}/cards"
query = {'key': key, 'token': token}

print("🔗 Connecting to Trello...")
response = requests.get(url, params=query)

def check_with_gemini(card_name, card_desc, checklists):
    prompt = f"""
    You are an AI Product Manager Validator. Your job is to strictly evaluate a Trello card and decide if it is ready for the engineering team.
    
    Card Name: {card_name}
    Card Description: {card_desc}
    Checklists: {checklists}

    CRITICAL RULES:
    The card MUST contain the standard template sections to be approved. Look closely for these three concepts:
    1. A 'User Story' (Who it is for and what they want).
    2. 'Tech Stack Constraints' (Frameworks, languages, or libraries to be used).
    3. 'Acceptance Criteria' or Requirements (A checklist of what must be built).

    If ANY of these three are missing, or if the description is too vague (e.g., "fix the button"), you must reject it.
    
    If rejected, write a professional 'missing' message telling the user exactly which sections they forgot to fill out from the PM Agent Template.

    Return ONLY a valid JSON object in this exact format:
    {{"ready": true, "missing": ""}} OR {{"ready": false, "missing": "Please add the Tech Stack Constraints to the ticket."}}
    """
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
            config={'response_mime_type': 'application/json'}
        )
        return json.loads(response.text)
    except Exception as e:
        print(f"❌ Gemini Audit Error: {e}")
        return {"ready": False, "missing": "Error communicating with AI Validator."}

def get_checklist_items(checklist_id):
    checklist_content = []
    url = f"https://api.trello.com/1/checklists/{checklist_id}"
    query = {'key': key, 'token': token}
    response = requests.get(url, params=query)
    if response.status_code == 200:
        checklist = response.json()
        items = [item['name'] for item in checklist.get('checkItems', [])]
        checklist_content.append(f"Checklist: {checklist['name']} with items: {', '.join(items)}")
    return "\n".join(checklist_content)

def post_trello_comment(card_id, comment):
    url = f"https://api.trello.com/1/cards/{card_id}/actions/comments"
    query = {'key': key, 'token': token, 'text': comment}
    requests.post(url, params=query)
    print(f"💬 Posted comment to Trello card.")

def commit_code_to_github(repo_name, file_path, content, task_name):
    auth = Auth.Token(os.getenv("GITHUB_TOKEN"))
    g = Github(auth=auth)
    repo = g.get_repo(repo_name)
    # repo = g.get_user().get_repo(repo_name)
    branch_name = f"ai-build-{task_name.lower().replace(' ', '-')}-{int(time.time())}"
    base_branch = "main"
    try:
        sb = repo.get_branch(base_branch)
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sb.commit.sha)
        repo.create_file(
            path=file_path,
            message=f"AI Build: {task_name}",
            content=content,
            branch=branch_name
        )
        pr = repo.create_pull(
            title=f"AI Suggestion: {task_name}",
            body=f"This PR was automatically generated by the PM Agent for the Trello task: {task_name}.",
            head=branch_name,
            base=base_branch
        )
        print(f"✅ PR Successfully Created: {pr.html_url}")
        return pr.html_url
    except Exception as e:
        print(f"❌ Error committing to GitHub: {e}")
        return None
    
def log_to_csv(card_name, prompt_version, status, pr_url):
    file_exists = os.path.isfile('logs.csv')
    with open('logs.csv', mode='a', newline='', encoding='utf-8') as file:
        # fieldnames = ['timestamp', 'card_name', 'prompt_version', 'status', 'pr_url']
        writer = csv.writer(file)
        if not file_exists:
            writer.writerow(['Timestamp', 'Card Name', 'Prompt Version', 'Status', 'PR URL'])
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        writer.writerow([timestamp, card_name, prompt_version, status, pr_url])

def get_attachment_url(card_id, attachment_id):
    url = f"https://api.trello.com/1/cards/{card_id}/attachments/{attachment_id}"
    res = requests.get(url, params={'key': key, 'token': token})
    return res.json().get('url') if res.status_code == 200 else None

def process_and_upload_image(card_id, attachment_id, card_name):
    img_url = get_attachment_url(card_id, attachment_id)
    if not img_url: 
        print("❌ Could not find attachment URL.")
        return None

    headers = {"Authorization": f'OAuth oauth_consumer_key="{key}", oauth_token="{token}"'}
    img_res = requests.get(img_url, headers=headers)
    
    if img_res.status_code == 200:
        image_bytes = io.BytesIO(img_res.content)
        pil_img = Image.open(image_bytes)
        pil_img.load()
        image_bytes.seek(0)

        s3_client = boto3.client(
            's3', 
            region_name=os.getenv("AWS_REGION_NAME"),
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY"),
            aws_secret_access_key=os.getenv("AWS_SECRET_KEY")
        )
        
        file_name = f"{card_name.replace(' ', '_')}.jpg"
        s3_client.upload_fileobj(image_bytes, os.getenv("AWS_S3_BUCKET_NAME"), file_name)
        print(f"☁️ Uploaded image to AWS S3: {file_name}")
        return pil_img 
    
    print(f"❌ Failed to download image from Trello. Status: {img_res.status_code}")
    return None


if response.status_code == 200:
    cards = response.json()
    print(f"📥 Successfully fetched {len(cards)} cards from the board.")
    
    for card in cards:
        if card['idList'] == '68bdf9ec4b3199a98b99d200':
            print(f"\n========================================")
            print(f"🔍 Processing Target Card: {card['name']}")
            print(f"========================================")
            
            print("📋 Fetching checklists...")
            all_checklists = ""
            for cl_id in card.get('idChecklists', []):
                all_checklists += get_checklist_items(cl_id) + "\n"
            
            print("🧠 Running Gemini Audit...")
            audit = check_with_gemini(card['name'], card['desc'], all_checklists)
            print(f"📊 Audit Result: {audit}")
            
            if not audit['ready']:
                print("⚠️ Audit Failed: Missing info. Commenting on Trello...")
                post_trello_comment(card['id'], f"Agent Alert: {audit['missing']}")
            else:
                print("✅ Audit Passed! Starting Image Processing...")
                ui_image = process_and_upload_image(card['id'], card['idAttachmentCover'], card['name'])
                
                if ui_image:
                    print("📸 Image ready. Asking Gemini to write code (This may take a few seconds)...")
                    prompt = f"Act as a Senior Developer. Generate code for: {card['name']}. Requirements: {card['desc']} {all_checklists}"
                    
                    generate_code = client.models.generate_content(
                        model='gemini-2.5-flash',
                        contents=[prompt, ui_image] 
                    ).text
                    
                    print("💻 Code generated! Pushing to GitHub...")
                    file_name = f"src/{card['name'].replace(' ', '_')}.py"
                    
                    pr_url = commit_code_to_github("HiyaMehta02/MCCAcademyApp", file_name, generate_code, card['name'])
                    
                    if pr_url:
                        post_trello_comment(card['id'], f"🚀 Build complete! PR created: {pr_url}")
                        target_list = '68bdf9f73eba23ffac9b4961'
                        moved = requests.put(f"https://api.trello.com/1/cards/{card['id']}", params={'key': key, 'token': token, 'idList': target_list})
                        log_to_csv(card['name'], "V1_Strict_Template", "Success", pr_url)
                        print(f"🎉 Pipeline finished successfully for {card['name']}!")
else:
    print(f"❌ Failed to connect to Trello: {response.text}")