import json
import os
import requests
from dotenv import load_dotenv
from google import genai
import requests
from github import Github
import time
import io
import boto3
from PIL import Image

load_dotenv()

key = os.getenv("TRELLO_API_KEY")
token = os.getenv("TRELLO_TOKEN")
board_id = os.getenv("TRELLO_BOARD_ID")
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

url = f"https://api.trello.com/1/boards/{board_id}/cards"

query = {
    'key': key,
    'token': token
}

response = requests.get(url, params=query)

def validate_card(card):
    info = []
    if not card['idAttachmentCover']:
        info.append("an image attachment (UI Mockup)")
    desc = card['desc']
    return True

def check_with_gemini(card):
    prompt = f"Audid this task: {card}. Is a tech stack mentioned? Return JSON {{'ready': bool, 'missing':str}}"
    response = client.models.generate_content(
        model='gemini-1.5-flash',
        contents=prompt,
        config={'response_mime_type': 'application/json'}
    )

    return json.loads(response.text)

def get_checklist_items(checklist_id):
    checklist_content = []
    url = f"https://api.trello.com/1/checklists/{checklist_id}"
    query = {
        'key': key,
        'token': token
    }
    response = requests.get(url, params=query)
    if response.status_code == 200:
        checklist = response.json()
        items = [item['name'] for item in checklist.get('checkItems', [])]
        checklist_content.append(f"Checklist: {checklist['name']} with items: {', '.join(items)}")

    return "\n".join(checklist_content)

def post_trello_comment(card_id, comment):
    url = f"https://api.trello.com/1/cards/{card_id}/actions/comments"
    query = {
        'key': key,
        'token': token,
        'text': comment
    }

    response = requests.post(url, params=query)

def commit_code_to_github(repo_name, file_path, content, task_name):
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_user().get_repo(repo_name)
    branch_name = f"ai-build-{task_name.lower().replace(' ', '-')}-{int(time.time())}"
    # in the future we can have the user set the base branch
    base_branch = "main"
    try:
        sb = repo.get_branch(base_branch)
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sb.commit.sha)
        repo.create_file(
            path=file_path,
            message=f"AI Build: {task_name}",
            content=content,
            branch=branch_name
        )

        pr = repo.create_pull(
            title=f"AI Suggestion: {task_name}",
            body=f"This PR was automatically generated by the PM Agent for the Trello task: {task_name}.",
            head=branch_name,
            base=base_branch
        )

        return pr.html_url

    except Exception as e:
        print(f"Error committing to GitHub: {e}")
        return None

def get_attachment_url(card_id, attachment_id):
    """Fetches the actual download URL for a Trello attachment ID."""
    url = f"https://api.trello.com/1/cards/{card_id}/attachments/{attachment_id}"
    res = requests.get(url, params={'key': key, 'token': token})
    return res.json().get('url') if res.status_code == 200 else None

def process_and_upload_image(card_id, attachment_id, card_name):
    """Downloads image from Trello and uploads to AWS S3."""
    img_url = get_attachment_url(card_id, attachment_id)
    if not img_url: return None

    headers = {"Authorization": f'OAuth oauth_consumer_key="{key}", oauth_token="{token}"'}
    img_res = requests.get(img_url, headers=headers)
    
    if img_res.status_code == 200:
        image_bytes = io.BytesIO(img_res.content)
        pil_img = Image.open(image_bytes)
        
        image_bytes.seek(0)

        s3_client = boto3.client(
            's3', 
            region_name=os.getenv("AWS_REGION_NAME"),
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY"),
            aws_secret_access_key=os.getenv("AWS_SECRET_KEY")
        )
        
        file_name = f"{card_name.replace(' ', '_')}.jpg"
        s3_client.upload_fileobj(image_bytes, os.getenv("AWS_S3_BUCKET_NAME"), file_name)
        
        return pil_img 
    return None

if response.status_code == 200:
    cards = response.json()
    for card in cards:
        if card['idList'] == '68bdf9ec4b3199a98b99d200':
            audit = check_with_gemini(card)
            
            all_checklists = ""
            for cl_id in card.get('idChecklists', []):
                all_checklists += get_checklist_items(cl_id) + "\n"
            
            if not audit['ready']:
                post_trello_comment(card['id'], f"Agent Alert: {audit['missing']}")
            else:
                ui_image = process_and_upload_image(card['id'], card['idAttachmentCover'], card['name'])
                
                if ui_image:
                    prompt = f"Act as a Senior Developer. Generate code for: {card['name']}. Requirements: {card['desc']} {all_checklists}"
                    
                    generate_code = client.models.generate_content(
                        model='gemini-1.5-flash',
                        contents=[prompt, ui_image] 
                    ).text
                    
                    file_name = f"src/{card['name'].replace(' ', '_')}.py"
                    pr_url = commit_code_to_github("PM_Agent_Repo", file_name, generate_code, card['name'])
                    
                    post_trello_comment(card['id'], f"Build complete! PR created: {pr_url}")